spring.application.name=TaxiBooking

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/TaxiBooking
spring.datasource.username=root
spring.datasource.password=Saurav@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
#jdbc:mysql://Taxihost:3306/